# Generated by Django 5.1.3 on 2024-11-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_email_remove_student_name_student_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='name', max_length=255),
        ),
    ]
